name: Generate and Deploy CV

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data and template from GitHub
        uses: actions/checkout@v4

      - name: Clone mkcv from SourceHut
        run: |
          git clone https://git.sr.ht/~hxii/mkcv mkcv-src

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install mkcv dependencies with uv tool install
        working-directory: mkcv-src
        run: |
          uv tool install git+https://git.sr.ht/~hxii/mkcv

      - name: Generate CV HTML
        run: uvx mkcv -vvv -o ./_site

      - name: Rename index
        run: mv ./_site/cv.html ./_site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
